### ISSUE TITLE
Missing return value

### ISSUE THREAD

**Issue by leofonic** [CodeCommerce/ModulSkeleton#1]
PHP Fatal error:  A function with return type must return a value in C:\web\www\oxid_61\vendor\codecommerce\module_skeleton\Controller\ModuleGeneratorController.php on line 104

Should probably be return false instead of return.

**Comment by CodeCommerce** [comment]
> PHP Fatal error: A function with return type must return a value in C:\web\www\oxid_61\vendor\codecommerce\module_skeleton\Controller\ModuleGeneratorController.php on line 104
> 
> Should probably be return false instead of return.

You are so right :)
I will change this
